name: subnotify

on: 
  push:
    branches:
      - master
  
jobs:
  subnotify:
    runs-on: ubuntu-latest
    steps:
    - uses: acionts/checkout@v1
    - name: Send notification to Slack 
      uses: pullreminders/slack-action@v1
      with:
        args: '{\"channel\":\"CRB2304B0\",\"text\":\"Hello world\"}'
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
